version: '3.8'

services:
  api_rec:
    build:
      context: ${PWD}
      dockerfile: docker/web/Dockerfile.local
    environment:
      APPLICATION_DB: ${APPLICATION_DB}
      MSSQL_USER: ${MSSQL_USER}
      MSSQL_HOSTNAME: "sqlserv-cross-selling"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PORT: ${MSSQL_PORT}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
    command: gunicorn -b :8001 -k uvicorn.workers.UvicornWorker --timeout 500 asgi:app
    volumes:
      - ${PWD}:/opt/code
  nginx_rec:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8081:8081
  cache:
    image: redis
    container_name: "redis-container"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    
volumes:
  redis_data: