version: '3.8'

services:
  # redis:
  #   image: redis
  #   container_name: "redis-container"
  #   ports:
  #     - "${REDIS_PORT}:6379"
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"